global:
  security:
    allowInsecureImages: true
kafka:
  image:
    repository: bitnamilegacy/kafka
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  metrics:
    kafka:
      enabled: false
